### ISSUE TITLE
打包 css和js

### ISSUE THREAD

**Issue by ddkwork** [epkgs/blink#1]
我测试了call js demo，载入一些css和js没有正确的打包进去，请假下如何正确操作

**Comment by edwinhuish** [comment]
之前修改过samples文件夹名，忘了改resources的路径。已修正 f560d213552c85fced12b326932ee905d7d8dfb5

注意需要在项目根目录执行：
```shell
go run ./samples/demo-call-js/
```

**Comment by ddkwork** [comment]
经过测试依然不生效，需要embed fs文件夹，编译后才能打包本地资源

**Comment by ddkwork** [comment]
此外，dll我感觉不要每个app都必须在根目录，应该去path找，这样就不会有n个40兆的dll了

**Comment by ddkwork** [comment]
另外一点是demo只有js返回go的，go发到js的api是那个

**Comment by edwinhuish** [comment]
> 经过测试依然不生效，需要embed fs文件夹，编译后才能打包本地资源

抱歉，之前没注意看你的描述。如果将资源打包进exe里，应该用 ` blink.Resource.Bind ` , `BindDir` 是为了不打包进最终文件，方便替换用的。

> 此外，dll我感觉不要每个app都必须在根目录，应该去path找，这样就不会有n个40兆的dll了

如果你要指定 `miniblink` 的dll 的路径的话，可以用 `NewAppWithConfig` 创建自定义的配置。本来有想进一步优化一下，可选是否将 `miniblink` 的dll打包进去，但不确定不同版本的dll兼容性如何，所以没优化。。。

> go发到js的api是那个

没有写demo，可以用这个函数：
```go
func (v *View) CallJsFunc(callback func(result any), funcName string, args ...any)
```

**Comment by ddkwork** [comment]
这个回调的参数太模糊了，不知道怎么用，字面意思result一定是js返回的，go send的话是发实例化的结构体对象还是json?funcname应该是区分json是哪种事件?arg是json body?



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年3月31日(周日) 晚上11:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




  
经过测试依然不生效，需要embed fs文件夹，编译后才能打包本地资源
  
抱歉，之前没注意看你的描述。如果将资源打包进exe里，应该用 blink.Resource.Bind , BindDir 是为了不打包进最终文件，方便替换用的。
  
此外，dll我感觉不要每个app都必须在根目录，应该去path找，这样就不会有n个40兆的dll了
  
如果你要指定 miniblink 的dll 的路径的话，可以用 NewAppWithConfig 创建自定义的配置。本来有想进一步优化一下，可选是否将 miniblink 的dll打包进去，但不确定不同版本的dll兼容性如何，所以没优化。。。
  
go发到js的api是那个
  
没有写demo，可以用这个函数：
 func (v *View) CallJsFunc(callback func(result any), funcName string, args ...any)

**Comment by ddkwork** [comment]
刚刚试了bind，参数类型不对啊，embed.fs 类型无法转为http那个的

cef太费了，期待您优化这个库

**Comment by edwinhuish** [comment]
抱歉，搞错了，这个函数就是 demo call-js 的例子。

```go
func (v *View) CallJsFunc(
  callback func(result any),  // JS 函数执行完成后的回调，在GO端执行。result在使用时需要断言
  funcName string,  // JS 的函数名称
  args ...any,  // JS 函数的参数
)
```

而至于 JS 调用 GO 的，暂想不到有什么除了 event 之外的应用场景，而且直接JS调用GO函数也会有安全性问题

**Comment by ddkwork** [comment]
应用场景有:网络抓包程序，go实现后端，把packet通过你的回调发送到bink控制的html界面上呈现在表格里面，此时需要go向js主动发送数据，



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 凌晨0:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




 
抱歉，搞错了，这个函数就是 demo call-js 的例子。
 func (v *View) CallJsFunc(   callback func(result any),  // JS 函数执行完成后的回调，在GO端执行。result在使用时需要断言   funcName string,  // JS 的函数名称   args ...any,  // JS 函数的参数 )
 
而至于 JS 调用 GO 的，暂想不到有什么除了 event 之外的应用场景，而且直接JS调用GO函数也会有安全性问题

**Comment by ddkwork** [comment]
至于go发给js之后，js也应该回复一下:确认已经把当前包数据呈现到表格了，这样就不会丢包了

**Comment by edwinhuish** [comment]
> 应用场景有:网络抓包程序，go实现后端，把packet通过你的回调发送到bink控制的html界面上呈现在表格里面，此时需要go向js主动发送数据，
> […](#)
> ---原始邮件--- 发件人: "Edwin ***@***.***&gt; 发送时间: 2024年4月1日(周一) 凌晨0:03 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1) 抱歉，搞错了，这个函数就是 demo call-js 的例子。 func (v *View) CallJsFunc( callback func(result any), // JS 函数执行完成后的回调，在GO端执行。result在使用时需要断言 funcName string, // JS 的函数名称 args ...any, // JS 函数的参数 ) 而至于 JS 调用 GO 的，暂想不到有什么除了 event 之外的应用场景，而且直接JS调用GO函数也会有安全性问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以使用`OnLoadUrlBegin`，具体看resources的bind实现。

或者 `AddEventListener`，具体看无边框demo的实现。

**Comment by ddkwork** [comment]
至于断言，我建议使用泛型，这样在发送方是可控的，至于js那边格式化表格的行数据，可以再次增加一个回调，此时可以直接发送结构体到js，回调里面格式化过程也是类型确定，可读性好，易理解。

**Comment by edwinhuish** [comment]
> 至于go发给js之后，js也应该回复一下:确认已经把当前包数据呈现到表格了，这样就不会丢包了

不是有callback吗？不懂你意思。

**Comment by edwinhuish** [comment]
> 至于断言，我建议使用泛型，这样在发送方是可控的，至于js那边格式化表格的行数据，可以再次增加一个回调，此时可以直接发送结构体到js，回调里面格式化过程也是类型确定，可读性好，易理解。

go 调用 JS 并获取JS 的返回值，其实我这边是分3步走的。也就是分为 ：

1. GO 调用 JS 函数
2. JS 调用 GO 预埋函数，发送序列化后的字符串到GO端。
3. GO 端接收到后，找出预存的callback，将结果字符串反序列化为 interface{}, 并将其作为参数运行callback。（此步貌似无法获知JS结果的实际类型）

之所以这样做，是因为免费版的`miniblink`和JS交互都依赖`JsExecState`, 如果传递10个参数，就得调用api 20次以上（每个变量的类型和值），然而`miniblink`是单线程的，而且有访问频率限制。。。

如果你这边有更好的解决方案，请告知。

**Comment by edwinhuish** [comment]
> 此外，dll我感觉不要每个app都必须在根目录，应该去path找，这样就不会有n个40兆的dll了

这个问题的确存在。我这边之前使用的是通过 `os.Getwd()` 去获取程序根目录，没考虑到在非程序根目录执行程序的情况。

准备用 `os.Executable()`去解决这个问题，唯一问题就是开发环境下通过执行 `go run` 执行时运行目录会在 C盘的临时目录下

**Comment by ddkwork** [comment]
我今天才第一天使用cef，等我使用下再和您研究。



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 凌晨0:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




  
至于断言，我建议使用泛型，这样在发送方是可控的，至于js那边格式化表格的行数据，可以再次增加一个回调，此时可以直接发送结构体到js，回调里面格式化过程也是类型确定，可读性好，易理解。
  
go 调用 JS 并获取JS 的返回值，其实我这边是分3步走的。也就是分为 ：
  
GO 调用 JS 函数
 
JS 调用 GO 预埋函数，发送序列化后的字符串到GO端。
 
GO 端接收到后，找出预存的callback，将结果字符串反序列化为 interface{}, 并将其作为参数运行callback。（此步貌似无法获知JS结果的实际类型）
  
之所以这样做，是因为免费版的miniblink和JS交互都依赖JsExecState, 如果传递10个参数，就得调用api 20次以上（每个变量的类型和值），然而miniblink是单线程的，而且有访问频率限制。。。
 
如果你这边有更好的解决方案，请告知。

**Comment by edwinhuish** [comment]
> 刚刚试了bind，参数类型不对啊，embed.fs 类型无法转为http那个的

明天我更新个示例。

**Comment by ddkwork** [comment]
总的一条，任意模块下执行go build命令都要能打包目录，并在非运行目录找到dll加载，这样编译的exe小，一个系统一个dll即可。目前我测试下来是go run找到html运行正常了，go build压根不打包他们，啥都没有，并且go build后的exe目录发现没有dll，直接panic了。使用体验很夸张



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 凌晨0:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




  
此外，dll我感觉不要每个app都必须在根目录，应该去path找，这样就不会有n个40兆的dll了
  
这个问题的确存在。我这边之前使用的是通过 os.Getwd() 去获取程序根目录，没考虑到在非程序根目录执行程序的情况。
 
准备用 os.Executable()去解决这个问题，唯一问题就是开发环境下通过执行 go run 执行时运行目录会在 C盘的临时目录下

**Comment by edwinhuish** [comment]
你这边如果能够提供具体复现问题的demo和步骤的话，我明天就能修复它

**Comment by ddkwork** [comment]
至于您说的要动态修改资源文件，我想网络存储更适合，它一般用于检测数据库是否需要更新之类。就是说需要动态加载和更新的东西我们应该放在影响编译的情况之外。go build之后的exe拷贝到另外一台机器找不到html和dll很那个



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 凌晨0:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




  
刚刚试了bind，参数类型不对啊，embed.fs 类型无法转为http那个的
  
明天我更新个示例。

**Comment by ddkwork** [comment]
4个demo都这样啊，你在每个demo的源码路径执行go build命令即可发现我说的情况。



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 凌晨0:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




 
你这边如果能够提供具体复现问题的demo和步骤的话，我明天就能修复它

**Comment by ddkwork** [comment]
我感觉你应该是没有把demo当做单独的模块。因为假如我是您的库的使用者，我不可能在您的仓库根目录去build的。为了方便起见，您只需把4个demo初始化为模块。我所阐述的一系列问题就复现了

**Comment by ddkwork** [comment]
你用工作区测试吧，4个demo，4个mod，加主模块，5个mod，sync之后分别build每个demo

**Comment by edwinhuish** [comment]
我这几个demo，都不是embed的。

另外如果你看一下我的demo的源码的话，你会发现每个BindDir旁边都有一行注释，是写了绝对路径的, go build 之后，资源缺失，报错是必然的。你实际项目应该按实际去修改。

至于embed的示例，我明天补上

**Comment by edwinhuish** [comment]
明天我将demo拆分到另外一个库，会更清晰易懂

**Comment by edwinhuish** [comment]
embed的，你可以查看我的devtools的实现

**Comment by ddkwork** [comment]
好的，等我联系一下cef之后，我将和您一起研究事件的泛型方式。我之前用它实现了一个树形，一个是入参的类型安全控制，另外一个是格式化的回调。测试了好几个工程，这套模式很好用。



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 凌晨0:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




 
我这几个demo，都不是embed的。
 
另外如果你看一下我的demo的源码的话，你会发现每个BindDir旁边都有一行注释，是写了绝对路径的, go build 之后，资源缺失，报错是必然的。你实际项目应该按实际去修改。
 
至于embed的示例，我明天补上

**Comment by edwinhuish** [comment]
> 好的，等我联系一下cef之后，我将和您一起研究事件的泛型方式。我之前用它实现了一个树形，一个是入参的类型安全控制，另外一个是格式化的回调。测试了好几个工程，这套模式很好用。
> […](#)
> ---原始邮件--- 发件人: "Edwin ***@***.***&gt; 发送时间: 2024年4月1日(周一) 凌晨0:48 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1) 我这几个demo，都不是embed的。 另外如果你看一下我的demo的源码的话，你会发现每个BindDir旁边都有一行注释，是写了绝对路径的, go build 之后，资源缺失，报错是必然的。你实际项目应该按实际去修改。 至于embed的示例，我明天补上 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

期待你的PR

**Comment by edwinhuish** [comment]
@ddkwork 已推了一波commit，应该已经可以满足你的需求。

**Comment by ddkwork** [comment]
> @ddkwork 已推了一波commit，应该已经可以满足你的需求。

刚刚测试加载ag-grid, 解析ts失败了

**Comment by edwinhuish** [comment]
解析 ts 失败是正常的，这个只是个精简版blink内核，不支持TS。

你应该将ag-grid项目编译为 JS， 以便更大的支持。

**Comment by ddkwork** [comment]
我就是调的js，js里面有一句调了ts，浏览器和cef都正常加载了它



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 下午2:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




 
解析 ts 失败是正常的，这个只是个精简版blink内核，不支持TS。
 
你应该将ag-grid项目编译为 JS， 以便更大的支持。

**Comment by edwinhuish** [comment]
另外，如果你的表格比较重，还是建议你用CEF，`miniblink`的各方面的性能以及兼容性不行。`miniblink`的优势是轻量，适合做一些小工具。

ag-grid我推荐你使用 [wails](https://github.com/wailsapp/wails)  或 [energy](https://github.com/energye/energy)

**Comment by ddkwork** [comment]
ag网格加载不成功我就不研究了。你要继续的话我给你个建议:dll不要embed，build的时候，搞成xcgui那种，找到dll路径之后loaddll即可，现在编译成了50mb，改成那种模式就每个app几兆就完了



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 下午2:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




 
解析 ts 失败是正常的，这个只是个精简版blink内核，不支持TS。
 
你应该将ag-grid项目编译为 JS， 以便更大的支持。

**Comment by ddkwork** [comment]
好的



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 下午2:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




 
另外，如果你的表格比较重，还是建议你用CEF，miniblink的各方面的性能以及兼容性不行。miniblink的优势是轻量，适合做一些小工具。
 
ag-grid我推荐你使用 wails  或 energy

**Comment by edwinhuish** [comment]
你看看我的readme，已经加了 `slim` 模式了。

`ag-grid` 我也用过。 浏览器和CEF是有nodejs环境的，但`miniblink`没有，它是精简版的。支持的特性不完整。

**Comment by ddkwork** [comment]
Energy昨天跑起来ag网格了，还是感觉太肥了。我准备研究下gioui



---原始邮件---
发件人: "Edwin ***@***.***&gt;
发送时间: 2024年4月1日(周一) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [epkgs/mini-blink] 打包 css和js (Issue #1)




 
你看看我的readme，已经加了 slim 模式了。
 
ag-grid 我也用过。 浏览器和CEF是有nodejs环境的，但miniblink没有，它是精简版的。支持的特性不完整。
